# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/grades-report',
                'doc_host': 'https://scott-yj-yang.github.io',
                'git_url': 'https://github.com/scott-yj-yang/grades-report',
                'lib_path': 'grades_report'},
  'syms': {'grades_report.core': {'grades_report.core.foo': ('core.html#foo', 'grades_report/core.py')}}}
